// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HomeController from "./home_controller"
application.register("home", HomeController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)

import ComponentController from "./component_controller"
application.register("component", ComponentController)
